version: "3"
services:
    rabbit:
        image: "rabbitmq:3-management"
        ports:
            - "5432:5432"
            - "15672:15672"
            - "5672:5672"
        networks:
            - "rabbit_net"
    sender:
        image: "sooobus/send:v1"
        networks:
            - "rabbit_net"
    receiver:
        image: "sooobus/receive:v1"
        networks:
            - "rabbit_net"
        depends_on:
            - "rabbit"
networks:
    rabbit_net:
